name: CI

on: [push]

jobs:
  format_check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Run format check
        run: go vet -v ./...
